name: Playwright Tests

on:
  push:
    branches:
      - '**'  # Trigger on any branch
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 'mobile'
          - 'desktop'
          - 'api'
          - 'user'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          # Extract the tag name from github.ref
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')

          # Run the test command if the tag matches
          if [[ "$TAG_NAME" == "${{ matrix.tag }}" ]]; then
            echo "Running tests for tag $TAG_NAME"
            npm run test:${{ matrix.tag }}
          else
            echo "Skipping tests for tag $TAG_NAME as it does not match ${{ matrix.tag }}"
            exit 0
          fi

      - name: Upload Playwright Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30